// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA6R2jJb8Jy49drZAzzAMuAJeYIt8UtjU',
    appId: '1:1013469356707:web:2508ac8c878f318ccc5516',
    messagingSenderId: '1013469356707',
    projectId: 'message-ef159',
    authDomain: 'message-ef159.firebaseapp.com',
    databaseURL: 'https://message-ef159-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'message-ef159.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgwj9ExjPc4mgEXTYlPLj4dhpveP6MV1k',
    appId: '1:1013469356707:android:ed1dfbdbaeaa6706cc5516',
    messagingSenderId: '1013469356707',
    projectId: 'message-ef159',
    databaseURL: 'https://message-ef159-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'message-ef159.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5jptxyApZou4DTw6nThC0f3CdC8R0Oo0',
    appId: '1:1013469356707:ios:3da53b123d7d22ebcc5516',
    messagingSenderId: '1013469356707',
    projectId: 'message-ef159',
    databaseURL: 'https://message-ef159-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'message-ef159.firebasestorage.app',
    iosClientId: '1013469356707-0toafne0d5dlvdk609lj9crcc4rjbo1n.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5jptxyApZou4DTw6nThC0f3CdC8R0Oo0',
    appId: '1:1013469356707:ios:3da53b123d7d22ebcc5516',
    messagingSenderId: '1013469356707',
    projectId: 'message-ef159',
    databaseURL: 'https://message-ef159-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'message-ef159.firebasestorage.app',
    iosClientId: '1013469356707-0toafne0d5dlvdk609lj9crcc4rjbo1n.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcnsuSBew33eOOSOEos0oVmYQ-Iq_43sw',
    appId: '1:1013469356707:web:67327af07f07cc6bcc5516',
    messagingSenderId: '1013469356707',
    projectId: 'message-ef159',
    authDomain: 'message-ef159.firebaseapp.com',
    databaseURL: 'https://message-ef159-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'message-ef159.firebasestorage.app',
  );
}
